### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by gipsyh** [aman-goel/avr#17]
passes/sat/freduce.cc:457:55: error: ‘numeric_limits’ is not a member of ‘std’

g++ (Ubuntu 13.2.0-4ubuntu3) 13.2.0

**Comment by tracymiao111** [comment]
Essentially, I think the problem is due to the lack of` #include <limits>`in **yosys/passes/sat/freduce.cc**(the latest yosys version has fixed this problem). 

There are several ways to fix this, one of the most convenient one (this may make your life easier) is modifying the segment related to yosys install in **build_deps.sh** into followings:


```
### Build and install yosys
pushd .
echo "  Installing Yosys (custom version) from https://github.com/aman-goel/yosys ..."
git clone https://github.com/aman-goel/yosys.git
cd yosys
sed -i '30i#include <limits>' passes/sat/freduce.cc
make config-gcc
make -j$(nproc) PREFIX="$PWD"
echo "  Done!"
popd
```

**Comment by tracymiao111** [comment]
> passes/sat/freduce.cc:457:55: error: ‘numeric_limits’ is not a member of ‘std’
> 
> g++ (Ubuntu 13.2.0-4ubuntu3) 13.2.0

Essentially, I think the problem is due to the lack of` #include <limits>`in **yosys/passes/sat/freduce.cc**(the latest yosys version has fixed this problem). 

There are several ways to fix this, one of the most convenient one (this may make your life easier) is modifying the segment related to yosys install in **build_deps.sh** into followings:


```
### Build and install yosys
pushd .
echo "  Installing Yosys (custom version) from https://github.com/aman-goel/yosys ..."
git clone https://github.com/aman-goel/yosys.git
cd yosys
sed -i '30i#include <limits>' passes/sat/freduce.cc
make config-gcc
make -j$(nproc) PREFIX="$PWD"
echo "  Done!"
popd
```

**Comment by gipsyh** [comment]
problem solved，thanks
